name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ← 加这一行，允许修改仓库内容
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          IMG_ALT: "随机照片"
          WIDTH: auto
          HEIGHT: 600px
